[package]
name = "hashbang"
version = "0.1.0"
authors = ["Alex Hornby <alex@hornby.org.uk>"]
description = "Binary fetcher and launcher"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
